
def set_latex(project_data):
    latex = r"""\documentclass[12pt,a4paper]{report}
    \usepackage{graphicx}
    \usepackage[utf8x]{inputenc}
    \usepackage[greek,english]{babel}
    \usepackage{hyperref}
    \hypersetup{
    colorlinks=true,
    linkcolor=blue,
    filecolor=magenta,
    urlcolor=cyan,
    }

    \newcommand{\en}{\selectlanguage{english}}
    \newcommand{\gr}{\selectlanguage{greek}}
    
    \begin{document}
    
    \begin{titlepage}
    \centering
    
    \begin{figure}[!htb]
    \begin{minipage}{0.48\textwidth}
    \centering
    \href{https://diavgeia.gov.gr/}{\includegraphics[width=.8\linewidth]{diavgeia_all_logo}}
    \end{minipage}\hfill
    \begin {minipage}{0.48\textwidth}
    \centering
    \href{http://platform.yourdatastories.eu/}{\includegraphics[width=.6\linewidth]{yds-logo}}
    \end{minipage}
    \end{figure}
    
    {\scshape\LARGE \href{http://143.233.226.60:8890/describe/?url=http://linkedeconomy.org/resource/PublicWork/299500}{\gr{Ανάπλαση Παραλίμνιου Χώρου Δήμου Περάματος Ιωαννίνων}} \par}
    \vspace{0.7cm}
    
    {\Large \gr Περιφερειακή ενότητα : \textbf{Περιφέρεια Ηπείρου}}
    \vspace{0.5cm}
    
    {\Large\bfseries \gr Αγοραστής : \par}
    {\Large \gr ΔΙΕΥΘΥΝΣΗ ΤΟΥΡΙΣΤΙΚΩΝ ΕΠΕΝΔΥΣΕΩΝ}
    \vspace{0.5cm}
    
    {\large \gr Ημερομηνία έναρξης : 2013-05-14 \par}
    {\large \gr Ημερομηνία λήξης : 2015-05-14 \par}
    \vspace{0.4cm}
    
    {\Large {\gr Ολοκλήρωση έργου : \textbf{95.8\%}} \par}
    \vspace{0.4cm}
    
    
    {\Large\itshape {\gr Περιγραφή :}\par}
    \raggedright
    {\normalsize {\gr Σκοπός του έργου είναι η ανάπλαση του παραλιμνίου χώρου που βρίσκεται στο Δήμο Περάματος Ιωαννίνων. Πιο αναλυτικά τα έργα που πρόκειται να γίνουν είναι τα εξής:
    1.	Διαμόρφωση κενού χώρου – πλατείας για τον οικίσκο του Περάματος.
    2.	Χώροι στάσης – ξεκούρασης – αναψυχής.
    3.	Παιδική χαρά.
    4.	Ξύλινες κατασκευές για ενημέρωση και εκπαίδευση σχετικά με το σπήλαιο,τον υδροβιότοπο, τη σχέση πόλη – λίμνη – νησί, κλπ.
    5.	Παρατηρητήριο.
    6.	Αθλητικές  εγκαταστάσεις με βοηθητικούς χώρους.
    7.	Κέντρο υποδοχής και τουριστικής πληροφόρησης. 
    8.	Τουαλέτες.
    9.	Χώρος στάθμευσης.}\par}\vspace{0.5cm}
    
    \centering
    \vfill
    generated by\par
    \textsc{yourdatastories.eu}
    
    {\footnotesize \today\par}
    \end{titlepage}
    
    
    
    \section*{Lorem Ipsum}
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras congue imperdiet posuere. Praesent a molestie ligula, non rutrum lectus. Morbi sit amet purus ac ante auctor condimentum. Vivamus consequat enim dui, at semper odio dignissim sit amet. Vestibulum malesuada tincidunt laoreet. Aliquam scelerisque lacus et orci fringilla fringilla. Nam in efficitur augue. Mauris sit amet dui sagittis, bibendum eros at, volutpat nulla. Sed vehicula lorem eget ligula maximus scelerisque. Fusce at ultrices libero. Etiam bibendum libero nec mi finibus dapibus. 
    
    \end{document}"""

    return latex